navikt/melosys-schema

schema/definitions-schema.json
schema/kontaktopplysninger-post-schema.json

Vi ønsker å kunne lagre kontaktnavn og kontaktorgnr uavnhengig av hverandre. Med andre ord, det skal være mulig å lagre et kontaktnavn uten å lagre et kontaktnr, og omvendt.

MELOSYS-2408 - Gjør kontaktopplysnings-felter nullable

---

mock_data/oppgaver-plukk/post/oppgaver-plukk-post.json
schema/definitions-schema.json
schema/oppgaver-plukk-post-schema.json

Oppgave-API støtter bare en enkelt behandlingstype og en enkelt sakstype.
melosys-web: https://github.com/navikt/melosys-web/pull/753

MELOSYS-3253 - Sakstyper og behandlingstyper ved plukk skal ikke være liste

---

.npmrc

Jenkins feiler ved npm install, prøver å hente fra GPR selv om pakker ligger i npm registry. Fjerner unødvendig .npmrc.

MELOSYS-2406 - Jenkins feiler ved npm install

---

mock_data/journalforing-opprett/post/opprett-post.json5
schema/journalforing-opprett-post-schema.json

Skrivefeil i forrige PR (#131), backend forventer `representererKode` (som har blitt brukt før i andre dto-er)

representantRepresenterer -> representererKode

---

Jenkinsfile

Den nye config-fila `navRepoAdeoMavenSettings` bruker repo.adeo.no i stedet for maven.adeo.no og henter maskerte credentials fra `nexus-uploader`. 
Maven-artifakter lastes opp til repoene:
- https://repo.adeo.no/#browse/browse/components:maven-releases
- https://repo.adeo.no/#browse/browse/components:maven-snapshots

Bytt til repo.adeo.no med credentials fra "nexus-uploader"

---

mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
schema/behandlingsgrunnlag-definitions.json

Legger til skjema for `luftfartBase` for arbeidssted ombord på fly. Fjerner `flyendePersonellHjemmebase` fra `arbeidNorge`, da denne virker overflødig med nytt skjema.
Har lagt til Francois som reviewer, siden han kjenner denne modellen fra jobb med mottak av elektronisk søknad fra Altinn.

Melosys 3784 luftfart base

---

mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
schema/behandlingsgrunnlag-definitions.json

Fikser en tabbe fra #161:
Jeg la feltet `luftfartBaser` til i skjemaene for `behandlingsgrunnlagData` og `soeknadData`, men siden også `sedGrunnlag` extender `behandlingsgrunnlagData` i `melosys-api`, må også denne ha det nye feltet for å validere.

Legg til luftfartBaser i sedGrunnlag

---

mock_data/vilkaar/post/vilkaar-post.json5
mock_data/vilkaar/vilkaar-bid-10.json5
mock_data/vilkaar/vilkaar-bid-11.json5
mock_data/vilkaar/vilkaar-bid-12.json5
mock_data/vilkaar/vilkaar-bid-14.json5
mock_data/vilkaar/vilkaar-bid-15.json5
mock_data/vilkaar/vilkaar-bid-16.json5
mock_data/vilkaar/vilkaar-bid-17.json5
mock_data/vilkaar/vilkaar-bid-3.json5
mock_data/vilkaar/vilkaar-bid-4.json5
mock_data/vilkaar/vilkaar-bid-5.json5
mock_data/vilkaar/vilkaar-bid-6.json5
mock_data/vilkaar/vilkaar-bid-7.json5
mock_data/vilkaar/vilkaar-bid-9.json5
schema/vilkaar-post-schema.json
schema/vilkaar-schema.json

- Gjør det mulig å oppgi en fritekstbegrunnelse til brev, og en fritekstbegrunnelse på engelsk til SED. Dette gjelder for øyeblikket ved sending av anmodning om unntak.

MELOSYS-3647 - Legg til felt i vilkår for engelsk fritekstbegrunnelse

---

mock_data/eessi-bucer/post/eessi-bucer-post.json5
schema/eessi-bucer-post-schema.json

Feltet heter `mottakerInstitusjoner` i koden rundt, både frontend og backend, så det gir mening at det heter det samme i payload/DTO også.

Endre felt mottakerIder til mottakerInstitusjoner

---

mock_data/behandlinger-behandling/behandling-bid-10.json5
mock_data/behandlinger-behandling/behandling-bid-11.json5
mock_data/behandlinger-behandling/behandling-bid-12.json5
mock_data/behandlinger-behandling/behandling-bid-13.json
mock_data/behandlinger-behandling/behandling-bid-14.json5
mock_data/behandlinger-behandling/behandling-bid-15.json5
mock_data/behandlinger-behandling/behandling-bid-16.json5
mock_data/behandlinger-behandling/behandling-bid-17.json5
mock_data/behandlinger-behandling/behandling-bid-3.json5
mock_data/behandlinger-behandling/behandling-bid-4.json5
mock_data/behandlinger-behandling/behandling-bid-5.json5
mock_data/behandlinger-behandling/behandling-bid-6.json5
mock_data/behandlinger-behandling/behandling-bid-7.json5
mock_data/behandlinger-behandling/behandling-bid-9.json5
mock_data/personer/fnr-17117802280.json5
mock_data/personer/fnr-19117220349.json5
mock_data/personer/fnr-28106600300.json5
mock_data/personer/fnr-30098000492.json5
schema/behandlinger-behandling-schema.json
schema/definitions-schema.json
schema/personer-schema.json

Legger til felter for vurdering av medfølgende barn. Feltene `alder` og `fnrAnnenForelder` er kun relevante for barn, og feltene `sivilstand` og `sivilstandGyldighetsperiodeFom` er kun relevante for ektefelle/samboer/partner, men det har jeg ikke lagd noen validering på.

Oppdater skjema for familieopplysninger

---

mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
schema/behandlingsgrunnlag-definitions.json

Endrer `medfolgendeBarn` til `medfolgendeFamilie` etter tilbakemelding på navikt/melosys-api#313, for å legge til rette for gjenbruk med folketrygden. Tenker at vi kanskje ikke ønsker å bruke/speile felles kodeverk for familierelasjoner hvis vi bare er interessert i å skille barn vs ektefelle/samboer/partner, men vet ikke om `relasjon` er et veldig beskrivende navn.

Endre skjema for medfølgende familiemedlemmer

---

schema/eessi-bucer-schema.json
schema/fagsaker-aktoerer-post-schema.json
schema/journalforing-opprett-post-schema.json
schema/journalforing-tilordne-post-schema.json

Endrer feil bruk av `id` i stedet for `$id` iht spec: https://json-schema.org/understanding-json-schema/structuring.html#id + fjerner et par trailing commas.
(Bakgrunnen er at jeg prøver ut et annet JSON schema-bibliotek for backend som er strengere på disse feilene.)

Fiks bruk av $id iht spec

---

mock_data/kodeverk-melosys-internt-folketrygden/kodeverk-melosys-internt-folketrygden.json5
schema/kodeverk-melosys-internt-folketrygden-schema.json

Legger til de nye kodeverkene som en del av begrunnelsene som blir hentet fra internt melosys kodeverk for FTLR. Tenker de hører hjemme der siden de også er begrunnelser.
For saken [MELOSYS-4213](https://jira.adeo.no/browse/MELOSYS-4213). Frontend trenger liste over begrunnelsene for barn og ektefelle/samboer. Siden frontend allerede henter kodeverk fra backend via `/kodeverk/melosys-internt/folketrygden`, legger jeg bare til de nye kodeverkene her.

Legger til de nye kodeverkene i begrunnelsene fra /kodeverk/melosys-internt/folketrygden

---

schema/behandlingsgrunnlag-definitions.json

Ser at utenlandske orgnr ikke nødvendigvis er 9 siffer, men kan inneholde bokstaver, bindestrek, og være annen lengde enn 9 tegn. Foreslår derfor denne endringen, hvor regex på 9 siffer fjernes for orgnr.
Det skal skape lite/ingen jobb backend i følge Andreas.

Utenlandske org.nr. er ikke nødvendigvis 9 siffer

---

schema/behandlinger-resultat-schema.json

Vedtakstypen vil være null om det ikke er fattet vedtak

MELOSYS-4436 - behandlingsresultat.vedtakstype er nullable

---

.github/workflows/build.yml
scripts/zipSchema2lib.js

Publiserer snapshot av schemabrancher, slik at det blir enklere å rulle ut melosys-api til testmiljø uten å merge schema først.
Maven-`job`en er hentet fra `publish.yml`.

Publiser maven snapshot

---

schema/behandlinger-status-post-schema.json

Brukte tidligere enum av strings. Var ikke valideringstester i api på denne før nå så ble ikke plukket opp.

Byttet til å bruke faktisk behandlingsstatus (fra kodeverk)

---

mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
schema/definitions-schema.json

I forbindelse med overgang til PDL har jeg tenkt at mengden av adresseformater fra PDL konverteres til adresseformater som Melosys kjenner allerede: strukturerte og ustrukturerte adresser (sjekket med fag).
Melosys trenger da nye felter i strukturerte adresser, postboks og tilleggsnavn.
Bør det være slik at disse er `required`? Funksjonelt sett er disse ikke påkrevd, men samtidig har vi vel ingen valgfrie felter
i schema?
Jeg oppdaterer ikke `strukturertAdresse` fordi den forsvinner med PDL (er også duplisering).

Postboks og tilleggsnavn i adresser

---

mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
mock_data/fagsaker-sok/sok-fnr-17117802280.json5
mock_data/fagsaker-sok/sok-fnr-19117220349.json5
mock_data/fagsaker-sok/sok-fnr-28106600300.json5
mock_data/fagsaker-sok/sok-fnr-30098000492.json5
mock_data/oppgaver-oversikt/oppgaver-oversikt.json5
schema/behandlingOversikter-definitions.json
schema/behandlingsgrunnlag-definitions.json
schema/definitions-schema.json
schema/oppgaver-definitions.json

Begynt å se på MELOSYS-4598.
Ved arbeid i flere land, ønskes det at man skal kunne krysse av i menypunkt for at land er enten ukjent eller alle EØS-land  ([skisse](https://www.figma.com/file/7valEmRFMgUIh4MIh7N0SC/Sidemeny?node-id=3581%3A1)). Dersom det velges alle/ukjente land, må man også kunne se det i `land`-feltet på oppgaveoversikten på forsiden og når man søker etter sak.

MELOSYS-4598 - Arbeidsland er ukjente eller alle EØS-land

---

mock_data/fagsaker-opprett/post/fagsaker-opprett-post.json5
mock_data/journalforing-opprett/post/opprett-post.json5
schema/fagsaker-opprett-post-schema.json
schema/journalforing-opprett-post-schema.json

Oppdatert schema nå som land i opprett(Ny)Sak er utvidet med `erUkjenteEllerAlleEosLand`

Melosys 4597 land utvidet med landkoder ukjente alle

---

mock_data/oppgaver-oversikt/oppgaver-oversikt.json5

Disse er lagt inn i oppgaver-oversikt manuelt, og jeg antar det på ett tidspunkt var nyttig å se hvordan forskjellige sakstyper kom til å se ut i oversikten. Siden disse faktiske er EU/EØS endrer jeg til at oversikten viser dette fra start.

trygdeavtale/folketrygden -> EU/SØS

---

mock_data/saksflyt-unntaksperioder-godkjenn/post/saksflyt-unntaksperioder-godkjenn-post.json5
schema/saksflyt-unntaksperioder-godkjenn-post-schema.json

Skal sende periode for endring av godkjent unntaksperiode direkte til endepunkt, i stedet for å endre perioden gjennom lovvalgsperiode-endepunkt som gjøres i dag.

MELOSYS-4647 - Endre periode ved godkjenning av unntaksperioder

---

mock_data/saksflyt-vedtak-fatt/post/saksflyt-vedtak-fatt-ftrl-post.json5
schema/saksflyt-vedtak-fatt-definitions.json

Var feil variabelnavn i fritekst i storbritannia-brev. Endret alle disse til å ha samme format for å rette opp og unngå samme feil i fremtiden.

Felles format på fritekstvariabler

---

mock_data/journalforing-opprett/post/opprett-post-bruker.json5
mock_data/journalforing-opprett/post/opprett-post-virksomhet.json5
mock_data/journalforing-tilordne/post/tilordne-post-bruker.json5
mock_data/journalforing-tilordne/post/tilordne-post-virksomhet.json5
schema/journalforing-opprett-post-schema.json
schema/journalforing-tilordne-post-schema.json

De er ikke required, men på grunn av hvordan validering-testene/(jave?) er satt opp må de i tillegg være nullable.

Vi kan sende med null i de tilfellene der de ikke er required
