navikt/melosys-schema

- mock_data/fagsaker/aktoerer/aktoer-snr-3.json
- mock_data/fagsaker/aktoerer/aktoer-snr-4.json
- mock_data/fagsaker/aktoerer/aktoer-snr-5.json
- mock_data/fagsaker/aktoerer/aktoer-snr-6.json
- mock_data/fagsaker/aktoerer/aktoer-snr-7.json
- mock_data/fagsaker/aktoerer/aktoer-snr-8.json
- mock_data/fagsaker/aktoerer/post/aktoer.json
- schema/aktoer-post-schema.json
- schema/aktoer-schema.json
- schema/definitions-schema.json
Vi vil benytte id fra aktoer-tabellen for å slette aktoerer.
> MELOSYS-2424 - Returner id for aktoer ved get og post

- package-lock.json
- package.json
> 1.8.0, legg til registrertDato og fnr for oppgaveoversikt

- mock_data/fagsaker/kontaktopplysninger/kontaktopplysninger-snr-3.json
- mock_data/fagsaker/kontaktopplysninger/kontaktopplysninger-snr-4.json
- mock_data/fagsaker/kontaktopplysninger/kontaktopplysninger-snr-5.json
- mock_data/fagsaker/kontaktopplysninger/kontaktopplysninger-snr-6.json
- mock_data/fagsaker/kontaktopplysninger/kontaktopplysninger-snr-7.json
- mock_data/fagsaker/kontaktopplysninger/kontaktopplysninger-snr-8.json
- package-lock.json
- package.json
- schema/kontaktopplysninger-schema.json
Relaxed corresponding schema to accept object and array and ignore
> MELOSYS-2419 Added support for loopup of juridiskorgnr in each mock file.

- schema/journalforing-opprett-schema.json
- schema/journalforing-tilordne-schema.json
så jeg benytter "roar" som placeholder.
> MELOSYS-2443.

- mock_data/soknader/soknad-bid-7.json
- schema/definitions-schema.json
- schema/soknad-dokument-definitions.json
Strukturert adresse må kunne være nullable for å kunne brukes i oppgitt adresse fra søknad
> Melosys-2719:Endre oppgittadresse til ikke påkrevd

- mock_data/behandlinger/behandling/behandling-bid-3.json
- mock_data/lovvalgsperioder/lovvalgsperiode-bid-10.json
- mock_data/lovvalgsperioder/lovvalgsperiode-bid-4.json
- mock_data/lovvalgsperioder/lovvalgsperiode-bid-9.json
- mock_data/saksflyt/unntaksperioder/post/saksflyt-unntaksperioder-post.json
- schema/behandlinger-behandling-schema.json
- schema/lovvalgsperioder-schema.json
- schema/saksflyt-unntaksperiode-post-schema.json
UTSENDELSE_OVER_24_MND => UTSENDELSE_OVER_24_MD
> MELOSYS-2087 Regisistrering av unntaksperioder

- mock_data/journalforing-opprett/post/opprett-post.json
- schema/journalforing-opprett-post-schema.json
Frontend: https://github.com/navikt/melosys-web/pull/730
> MELOSYS-3107 - Nye felt ved journalføring av anmodning om unntak

- schema/journalforing-opprett-post-schema.json
web: https://github.com/navikt/melosys-web/pull/756
> MELOSYS-3276 - Setter periode og land nullable i journalforing-opprett-post-schema

- mock_data/behandlinger/behandling-bid-12.json5
- mock_data/behandlinger/behandling-bid-3.json5
- mock_data/behandlinger/behandling-bid-4.json5
- mock_data/behandlinger/behandling-bid-6.json5
- mock_data/behandlinger/behandling-bid-7.json5
- mock_data/behandlinger/behandling-bid-8.json5
- mock_data/behandlinger/behandling-bid-9.json5
- mock_data/personer/fnr-28106600300.json5
- mock_data/personer/fnr-30098000492.json5
- mock_data/soknader/soknad-bid-12.json5
- mock_data/soknader/soknad-bid-4.json5
Gatenummer er nummeret på gaten og er ikke så relevant for saksbehandling.
> Endrer mock-data for husnummer og gatenummer

- mock_data/fagsaker-sok/sok-fnr-30098000492.json5
La til mock data med behandlingsOversikter.behandlingstype => "behandlingstype":{"kode":"SOEKNAD","term":"Søknad"}
> MELOSYS-3106 Mockdata med behandlingsOversikter.behandlingstype=> SOEKNAD

- .eslintrc
- package-lock.json
- package.json
- scripts/schema.test.js
Testfeil gir informasjon om feilet test, men avslutter prosess med kode 0. Workflow fortsetter derfor selv om tester feilet. Denne PRen fikser dette.
> MELOSYS-3406 - Legg til jest

- schema/fagsaker-kontaktopplysninger-schema.json
Denne PRen tilrettelegger for at man kan registrere kontaktopplysninger uten orgnr.
> MELOSYS-3443 - Kontaktorgnr kan være null

- mock_data/journalforing-opprett/post/opprett-post.json5
- mock_data/journalforing-tilordne/post/tilordne-post.json5
- schema/journalforing-opprett-post-schema.json
- schema/journalforing-tilordne-post-schema.json
https://github.com/navikt/melosys-web/pull/827
> MELOSYS-3106 - Legg til mottattDato i jfr-posts

- mock_data/oppgaver-sok/sok-fnr-17117802280.json5
- mock_data/oppgaver-sok/sok-fnr-19117220349.json5
- mock_data/oppgaver-sok/sok-fnr-28106600300.json5
- mock_data/oppgaver-sok/sok-fnr-30098000492.json5
- mock_data/oppgaver-sok/sok-fnr-33333333333.json5
- schema/oppgaver-sok-schema.json
- Bytter fra term til kode for tema i oppgaver-sok
> MELOSYS-3468 - Oppgaver-sok: tema er kode, ikke term

- schema/definitions-schema.json
Lagt til i https://confluence.adeo.no/display/TEESSI/Kodeverk+i+Melosys 16. januar.
> Legg til ny kodeverdi i VedtaksTyper

- mock_data/oppgaver-sok/sok-fnr-17117802280.json5
- mock_data/oppgaver-sok/sok-fnr-19117220349.json5
- mock_data/oppgaver-sok/sok-fnr-28106600300.json5
- mock_data/oppgaver-sok/sok-fnr-30098000492.json5
- mock_data/oppgaver-sok/sok-fnr-33333333333.json5
- schema/oppgaver-sok-schema.json
- Frontend ønsker ikke å tillate at det opprettes en sak på en oppgave som ikke har en journalpost(da vil journalpostID være null).
> MELOSYS-3576 - Legg til jounalpostID for oppgaver/sok

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
- Endrer litt på mock data slik at frontend ikke krasjer når bid14 åpnes
> MELOSYS-3713 - BehandlingID 14 skal ha sedgrunnlag

- mock_data/fagsaker-utpek/post/fagsaker-utpek-post.json5
- mock_data/saksflyt-anmodningsperioder-bestill/post/saksflyt-anmodningsperioder-bestill-post.json
- mock_data/saksflyt-vedtak-endre/post/saksflyt-vedtak-endre-post.json
- mock_data/saksflyt-vedtak-fatt/post/saksflyt-vedtak-fatt-post.json5
- schema/fagsaker-utpek-post-schema.json
- schema/saksflyt-anmodningsperioder-bestill-post-schema.json
- schema/saksflyt-vedtak-endre-post-schema.json
- schema/saksflyt-vedtak-fatt-post-schema.json
Nye felt fritekstSed for fritekst til SED ved anmodning om unntak, vedtak og utpeking av annet land
> Fritekst til SED

- mock_data/vilkaar/vilkaar-bid-10.json5
- mock_data/vilkaar/vilkaar-bid-11.json5
- mock_data/vilkaar/vilkaar-bid-12.json5
- mock_data/vilkaar/vilkaar-bid-14.json5
- mock_data/vilkaar/vilkaar-bid-15.json5
- mock_data/vilkaar/vilkaar-bid-16.json5
- mock_data/vilkaar/vilkaar-bid-17.json5
- mock_data/vilkaar/vilkaar-bid-3.json5
- mock_data/vilkaar/vilkaar-bid-4.json5
- mock_data/vilkaar/vilkaar-bid-5.json5
- mock_data/vilkaar/vilkaar-bid-6.json5
- mock_data/vilkaar/vilkaar-bid-7.json5
- mock_data/vilkaar/vilkaar-bid-9.json5
- Legger til oppfylte inngangsvilkaar for alle behandlinger i mock data slik at melosys-web fungerer ved bruk av melosys-mock som backend.
> MELOSYS-3701 - Legg til innvangsvilkaar for mock data

- mock_data/fagsaker-utpek/post/fagsaker-utpek-post.json5
- schema/fagsaker-utpek-post-schema.json
- Venter med merge til backend er klar
> MELOSYS-3728 - Fritekst for orienteringsbrev ved utpeking

- schema/behandlingsgrunnlag-definitions.json
- Jeg glemte å legge til i #162
> Legger til enum-verdi null for typeFlyvninger

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
- mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
- schema/behandlingsgrunnlag-definitions.json
Fjerner `arbeidNorge`, som diskutert på Slack, siden det ikke brukes til noe.
> Fjern arbeidNorge fra behandlingsgrunnlag

- mock_data/fagsaker-sok/post/sok-fnr-17117802280.json5
- mock_data/fagsaker-sok/post/sok-saksnummer-MEL-2.json5
- schema/fagsaker-sok-post-schema.json
- scripts/test/fagsaker/sok.js
POST-body for at søke-kriterier ikke skal logges i load-balancer. Legger også til felt for saksnummer
> Schema for nytt endepunkt for søk på fagsaker

- mock_data/dokumenter-oversikt/oversikt.json5
- mock_data/eessi-bucer/post/eessi-bucer-post.json5
- schema/eessi-bucer-post-schema.json
Frontend: https://github.com/navikt/melosys-web/pull/1013
Backend: https://github.com/navikt/melosys-api/pull/254
> MELOSYS-3535 - Vedlegg ved opprettelse av BUC

- mock_data/eessi-bucer/post/eessi-bucer-post.json5
- schema/eessi-bucer-post-schema.json
Endrer mottaker fra streng til liste med strenger.
> Legg til rette for liste med mottakerIder i opprett BUC

- mock_data/dokumenter-pdf-utkast-brev/post/utkast_og_opprett-post.json5
- schema/dokumenter-pdf-utkast-brev-post-schema.json
Kommer PR på frontend og backend
> MELOSYS-4011 - Send ytterligereInformasjon som eget felt for Brev A001

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
Oppdaterer mock-data. Behandlingsgrunnlagtype brukes ikke av frontend enda.
> MELOSYS-4171 - Nye koder behandlingsgrunnlagtype

- schema/behandlingsgrunnlag-definitions.json
> MELOSYS-3852 - Overgangsregelbestemmelser skal postes som kode

- schema/behandlingsgrunnlag-definitions.json
- schema/behandlingsgrunnlag-schema.json
- schema/definitions-schema.json
- schema/lovvalgsperioder-post-schema.json
Samme som det eksisterende søknad-schemaet, bare med trygdedekning i tillegg
> Legger til schema for søknad-folketrygden

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
- mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
- mock_data/personer/fnr-31031779459.json5
- schema/behandlingsgrunnlag-definitions.json
Usikker på hvordan dette eventuelt forholder seg til `medfolgendeFamilie` som vi har fra før, og som er i bruk frontend, men ikke har noe logikk knytta til seg backend (annet enn til å hente ut alle fnr).
> Legg til skjema for medfølgende barn

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-810072512.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-873152362.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-910099035.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-910253158.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-912499693.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-923609016.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-943049467.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-967032271.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-973063804.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-982683955.json5
- mock_data/fagsaker-kontaktopplysninger/kontaktopplysninger-snr-2-jorgnr-991492704.json5
> Melosys 4209

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
- mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
- schema/behandlingsgrunnlag-definitions.json
> Legg til felter i behandlingsgrunnlag, juridisk arbeidsgiver Norge

- mock_data/avklartefakta-oppsummering/avklartefakta-oppsummering-bid-2.json5
- mock_data/avklartefakta-virksomheter/post/avklartefakta-virksomheter-post.json5
- schema/avklartefakta-oppsummering-schema.json
- schema/avklartefakta-virksomheter-post-schema.json
- schema/definitions-schema.json
> Bruker virksomhetIDer konsekvent

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-10.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-12.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-15.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-16.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-17.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-18.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-3.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-4.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-5.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-6.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-7.json5
- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-9.json5
- mock_data/behandlingsgrunnlag/post/behandlingsgrunnlag-post.json5
- schema/behandlingsgrunnlag-definitions.json
- Endringer i behandlingsgrunnlag for arbeidssted på land og maritimt arbeid
- `innretningstype` - navn fra kodeverk
> MELOSYS-4221 - Legger til hittil ubrukte felter fra altinn-søknad(Arbeidssteder)

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-2.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-2.json5
- mock_data/fagsaker-aktoerer/post/response-snr-2.json5
Småendringer som har vært lokalt på maskinen en stund nå. Skaper feil i bl.a. fullmektig-menypunktet.
> Småendringer til behandling 2

- mock_data/dokumenter-v2-opprett/post/mangelbrev_arbeidsgiver-post.json5
- mock_data/dokumenter-v2-opprett/post/mangelbrev_bruker-post.json5
- mock_data/dokumenter-v2-opprett/post/melding_forventet_saksbehandlingstid_soknad-post.json5
- mock_data/dokumenter-v2-tilgjengelige-maler/tilgjengelige-maler.json5
- mock_data/dokumenter-v2-utkast/post/mangelbrev_arbeidsgiver-post.json5
- mock_data/dokumenter-v2-utkast/post/mangelbrev_bruker-post.json5
- mock_data/dokumenter-v2-utkast/post/melding_forventet_saksbehandlingstid_soknad-post.json5
- schema/dokumenter-pdf-utkast-brev-post-schema.json
- schema/dokumenter-v2-opprett-post-schema.json
- schema/dokumenter-v2-tilgjengelige-maler-schema.json
- schema/dokumenter-v2-utkast-post-schema.json
Endringer som kommer av PR-kommentarer til [PR-503](https://github.com/navikt/melosys-api/pull/503)
> Melosys 4131 backend tilpasninger skaper endringer

- .github/workflows/build.yml
- .github/workflows/publish.yml
- package-lock.json
- package.json
- npm run schema -> npm test
- mer intuitivt at testscript heter "test", og følger konvensjon i andre repo
> Testscript navneendring

- schema/dokumenter-v2-opprett-post-schema.json
- schema/dokumenter-v2-utkast-post-schema.json
> Oppdatert schema for bestilling av brev

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-19.json5
- schema/behandlingsgrunnlag-definitions.json
- schema/behandlingsgrunnlag-post-schema.json
- schema/behandlingsgrunnlag-schema.json
- schema/definitions-schema.json
[Jira-link](https://jira.adeo.no/browse/MELOSYS-4729)
> Legger til representantIUtlandet i trygdeavtale-beh.grunnlag

- mock_data/behandlingsgrunnlag/behandlingsgrunnlag-bid-14.json5
- schema/behandlingsgrunnlag-definitions.json
https://jira.adeo.no/browse/MELOSYS-4730
> Fnr for medfolgende barn kan være fødselsdato

- mock_data/dokumenter-v2-mulige-mottakere/mulige-mottakere-ftrl-innvilgelse.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-12.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-15.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-16.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-17.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-2.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-3.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-4.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-5.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-6.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-7.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-8.json5
- mock_data/fagsaker-aktoerer/aktoer-snr-MEL-554.json5
- schema/dokumenter-opprett-post-schema.json
- schema/dokumenter-pdf-utkast-brev-post-schema.json
- schema/dokumenter-v2-mulige-mottakere-schema.json
- schema/dokumenter-v2-opprett-post-schema.json
- schema/dokumenter-v2-utkast-post-schema.json
- schema/fagsaker-aktoerer-post-schema.json
- schema/fagsaker-aktoerer-schema.json
- schema/saksflyt-vedtak-fatt-definitions.json
Endring i kodeverk: https://github.com/navikt/melosys-kodeverk/pull/201
> Endret aktoerrolle i kodeverk, oppdatert verdi her for å gjenspeile

- mock_data/saksflyt-vedtak-fatt/post/saksflyt-vedtak-fatt-eos-post.json5
- mock_data/saksflyt-vedtak-fatt/post/saksflyt-vedtak-fatt-ftrl-post.json5
- mock_data/saksflyt-vedtak-fatt/post/saksflyt-vedtak-fatt-trygdeavtale-post.json5
- schema/saksflyt-vedtak-fatt-definitions.json
- schema/saksflyt-vedtak-fatt-post-schema.json
https://nav-it.slack.com/archives/C01CFP7SL4Q/p1643703244878279?thread_ts=1643618770.660539&cid=C01CFP7SL4Q
> Sender med revurder_bakgrunn for FTRL og Trygdeavtale også

- mock_data/behandlinger-behandling/post/behandlinger-behandling-post.json5
- mock_data/behandlinger-endrebehandlingstema/muligebehandlingstema-bid-2.json5
- mock_data/behandlinger-status/muligebehandlingsstatuser-bid-4.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-10.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-11.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-12.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-13.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-14.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-15.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-16.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-17.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-19.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-2.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-3.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-4.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-5.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-6.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-7.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-8.json5
- mock_data/behandlinger-type/muligebehandlingstyper-bid-9.json5
- schema/behandlinger-behandling-post-schema.json
- schema/behandlinger-type-schema.json
- `muligeBehandlingstyper`: respons for nytt get-endepunkt
- `endreBehandling`: request for nytt post-endepunkt
> Melosys 4873 mulige behandlingstyper

- schema/anmodningsperioder-svar-post-schema.json
- schema/anmodningsperioder-svar-schema.json
- schema/avklartefakta-definitions.json
- schema/behandlinger-resultat-schema.json
- schema/definitions-schema.json
- schema/dokumenter-opprett-post-schema.json
- schema/dokumenter-pdf-utkast-brev-post-schema.json
- schema/dokumenter-pdf-utkast-sed-post-schema.json
- schema/dokumenter-v2-opprett-post-schema.json
- schema/dokumenter-v2-utkast-post-schema.json
- schema/fagsaker-henlegg-post-schema.json
- schema/fagsaker-henleggvideresend-post-schema.json
- schema/fagsaker-utpek-post-schema.json
- schema/saksflyt-anmodningsperioder-bestill-post-schema.json
- schema/saksflyt-unntaksperioder-godkjenn-post-schema.json
- schema/saksflyt-unntaksperioder-ikkegodkjenn-post-schema.json
- schema/saksflyt-utpeking-avvis-post-schema.json
- schema/saksflyt-vedtak-endre-post-schema.json
- schema/saksflyt-vedtak-fatt-definitions.json
- schema/vilkaar-post-schema.json
- schema/vilkaar-schema.json
Kan sende med nyVurderingBakgrunn direkte til opprett og utkast, på lik linje som ved fatting av vedtak.
> Forhåndsvise ny-vurdering brev hadde ikke fått nyVurderingBakgrunn

- mock_data/fagsaker-sok/post/sok-fnr-17117802280.json5
- mock_data/fagsaker-sok/post/sok-orgnr-999999999.json5
- mock_data/fagsaker-sok/post/sok-saksnummer-MEL-2.json5
- mock_data/fagsaker-sok/sok-fnr-17117802280.json5
- mock_data/fagsaker-sok/sok-fnr-19117220349.json5
- mock_data/fagsaker-sok/sok-fnr-28106600300.json5
- mock_data/fagsaker-sok/sok-fnr-30098000492.json5
- mock_data/fagsaker/snr-11.json5
- mock_data/fagsaker/snr-12.json5
- mock_data/fagsaker/snr-13.json5
- mock_data/fagsaker/snr-14.json5
- mock_data/fagsaker/snr-15.json5
- mock_data/fagsaker/snr-16.json5
- mock_data/fagsaker/snr-17.json5
- mock_data/fagsaker/snr-19.json5
- mock_data/fagsaker/snr-2.json5
- mock_data/fagsaker/snr-3.json5
- mock_data/fagsaker/snr-4.json5
- mock_data/fagsaker/snr-5.json5
- mock_data/fagsaker/snr-6.json5
- mock_data/fagsaker/snr-7.json5
- mock_data/fagsaker/snr-8.json5
- mock_data/oppgaver-oversikt/oppgaver-oversikt.json5
- schema/definitions-schema.json
- schema/fagsaker-schema.json
- schema/fagsaker-sok-post-schema.json
- schema/fagsaker-sok-schema.json
- schema/oppgaver-definitions.json
https://jira.adeo.no/browse/MELOSYS-5127
https://github.com/navikt/melosys-api/pull/1207
> Melosys 5127 tilpassinger for virksomhet

- mock_data/journalforing/DOK_3789.json5
- mock_data/journalforing/DOK_9997.json5
- mock_data/journalforing/DOK_9998.json5
- schema/journalforing-schema.json
journalpostDto i backend har fått det nye feltet virksomhetOrgnr og e…ndrer erBrukerAvsender til erHovedpartAvsender
https://github.com/navikt/melosys-api/pull/1207#discussion_r888063681
> Tilpassinger virksomhet journalpostdto
